## Smith Waterman Algorithm

In [3]:
import numpy as np

sequence_1 = "ATGC"
sequence_2 = "ATC"

main_matrix = np.zeros((len(sequence_1)+1,len(sequence_2)+1))
match_checker_matrix = np.zeros((len(sequence_1),len(sequence_2)))

match_reward = 2
mismatch_penalty = 1
gap_penalty = 0

for i in range(len(sequence_1)):
    for j in range(len(sequence_2)):
        if sequence_1[i] == sequence_2[j]:
            match_checker_matrix[i][j]= match_reward
        else:
            match_checker_matrix[i][j]= mismatch_penalty

#print(match_checker_matrix)

#STEP 2 : MATRIX FILLING
for i in range(1,len(sequence_1)+1):
    for j in range(1,len(sequence_2)+1):

        main_matrix[i][j] = max(max(main_matrix[i][j-1]+ gap_penalty, 0), max(main_matrix[i-1][j]+gap_penalty, 0), max(main_matrix[i-1][j-1]+match_checker_matrix[i-1][j-1], 0))

print(main_matrix, '\n')

# STEP 3 : TRACEBACK

def traceback(s1, s2, x, y):

    aligned_1 = ''
    aligned_2 = ''

    while (x > 0 and y > 0 and main_matrix[x][y] != 0):

        if (x >0 and y > 0 and main_matrix[x][y] == main_matrix[x-1][y-1]+ match_checker_matrix[x-1][y-1]):

            aligned_1 = sequence_1[x-1] + aligned_1
            aligned_2 = sequence_2[y-1] + aligned_2

            x = x - 1
            y = y - 1

        elif(x > 0 and main_matrix[x][y] == main_matrix[x-1][y] + gap_penalty):
            aligned_1 = sequence_1[x-1] + aligned_1
            aligned_2 = "-" + aligned_2

            x = x -1
        else:
            aligned_1 = "-" + aligned_1
            aligned_2 = sequence_2[y-1] + aligned_2

            y = y - 1

    return aligned_1, aligned_2


max_value = np.max(main_matrix)
max_positions = np.argwhere(main_matrix == max_value)
#print(max_positions)

for max_position in max_positions:
    x, y = max_position
    aligned_1, aligned_2 = traceback(sequence_1, sequence_2, x,y)
    print(f'Algined Sequences:')
    print(x,y)
    print(aligned_1)
    print(aligned_2)

print(aligned_1)
print(aligned_2)


[[0. 0. 0. 0.]
 [0. 2. 2. 2.]
 [0. 2. 4. 4.]
 [0. 2. 4. 5.]
 [0. 2. 4. 6.]] 

Algined Sequences:
4 3
ATGC
AT-C
ATGC
AT-C


# Smith Waterman in Binary (Matrix Filling)

In [2]:
# A = 00, T = 01, G = 10, C = 11
import numpy as np

sequence1 = "00011011"  #ATGC
sequence2 = "000111"  #ATC

rows = (len(sequence1) // 2) + 1
cols = (len(sequence2) // 2) + 1
main = np.zeros((rows, cols), dtype=int)

match_reward = 2
mismatch_penalty = 1
gap_penalty = 0

for i in range(1,rows):
    for j in range(1,cols):
        value_from_left = max(main[i, j-1] + gap_penalty, 0)
        value_from_right = max(main[i-1, j] + gap_penalty, 0)
        if sequence1[2*i - 1] == sequence2[2*j - 1] and sequence1[2*i - 2] == sequence2[2*j - 2]:
            check = match_reward
        else:
            check = mismatch_penalty
        value_from_diag = max(main[i-1, j-1] + check, 0)

        main[i,j] = max(value_from_diag, value_from_left, value_from_right)

print(main)


[[0 0 0 0]
 [0 2 2 2]
 [0 2 4 4]
 [0 2 4 5]
 [0 2 4 6]]
